# Generated by Django 3.0.5 on 2021-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20211109_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
    ]
